CREATE TABLE [HR].[HR_EMP_INFO_V](
	[POST_NUMBER] [nvarchar](150) NULL,
	[POST_TITLE_LONG_DESC] [nvarchar](240) NULL,
	[POST_TITLE_SHORT_DESC] [nvarchar](150) NULL,
	[POST_TYPE_LONG_DESC] [nvarchar](80) NULL,
	[GRADE] [nvarchar](240) NULL,
	[PF_NO] [nvarchar](30) NULL,
	[EMPLOYEE_NAME] [nvarchar](240) NULL,
	[FIRST_NAME] [nvarchar](150) NULL,
	[FAMILY_NAME] [nvarchar](150) NULL,
	[ARABIC_FIRST_NAME] [nvarchar](150) NULL,
	[ARABIC_FATHER_NAME] [nvarchar](150) NULL,
	[ARABIC_GRANDFATHER_NAME] [nvarchar](150) NULL,
	[ARABIC_FAMILY_NAME] [nvarchar](150) NULL,
	[CURRENT_NATIONALITY] [nvarchar](80) NULL,
	[LOCATION] [nvarchar](60) NULL,
	[GROUPS] [nvarchar](4000) NULL,
	[DIVISION] [nvarchar](4000) NULL,
	[DEPARTMENT] [nvarchar](4000) NULL,
	[UNIT] [nvarchar](4000) NULL,
	[SECTION] [nvarchar](4000) NULL,
	[POST_DT] [datetime2](7) NULL,
	[ENGAGEMENT_TYPE] [nvarchar](60) NULL,
	[ENG_DT] [datetime2](7) NULL,
	[DIV_LONG_DESC] [nvarchar](4000) NULL,
	[DIV_SHORT_DESC] [nvarchar](4000) NULL,
	[DEP_LONG_DESC] [nvarchar](4000) NULL,
	[DEP_SHORT_DESC] [nvarchar](4000) NULL,
	[SEC_LONG_DESC] [nvarchar](4000) NULL,
	[SEC_SHORT_DESC] [nvarchar](4000) NULL,
	[GRP_CODES_LONG_DESC] [nvarchar](4000) NULL,
	[GRP_CODES_SHORT_DESC] [nvarchar](4000) NULL,
	[TEAM_LONG_DESC] [nvarchar](4000) NULL,
	[TEAM_SHORT_DESC] [nvarchar](4000) NULL,
	[BIRTH_DATE] [datetime2](7) NULL,
	[GENDER] [nvarchar](80) NULL,
	[POST_END_DATE] [datetime2](7) NULL,
	[EMAIL] [nvarchar](240) NULL,
	[OFFICE_TELEPHONE_NUMBER] [nvarchar](45) NULL,
	[OFFICE_LOCATION] [nvarchar](45) NULL,
	[MOBILE] [nvarchar](4000) NULL,
	[SUPERVISOR_POST_NUMBER] [nvarchar](150) NULL,
	[TERMINATION_DATE] [datetime2](7) NULL,
	[TERMINATION_REASON] [nvarchar](80) NULL,
	[LAST_UPDATE_DATE] [datetime2](7) NULL,
	[OBJECT_VERSION_NUMBER] [numeric](9, 0) NULL,
	[SUPERVISOR_PF_NO_TL_AND_ABOVE] [nvarchar](4000) NULL,
	[ACTING_SUPERVISOR_PF_NO] [nvarchar](30) NULL,
	[ACTING_SUP_START_DATE] [datetime2](7) NULL,
	[ACTING_SUP_END_DATE] [datetime2](7) NULL,
	[IS_VPN_AND_ABOVE] [nvarchar](4000) NULL,
	[EMPLOYMENT_TYPE] [nvarchar](60) NULL,
	[PARENT_COMPANY] [nvarchar](60) NULL,
	[ORGANIZATION_ID] [numeric](15, 0) NULL,
	[POSITION_ID] [numeric](15, 0) NULL
) ON [PRIMARY]

 
 

