
CREATE TABLE [HR].[POSITION_HIREARCHY](
	[POSITION_NAME] [nvarchar](4000) NULL,
	[POSITION_ORG_LEVEL] [nvarchar](4000) NULL,
	[ACTING_POSITION_NAME] [nvarchar](240) NULL,
	[REPORTING_TO_POSITION_NAME] [nvarchar](4000) NULL,
	[REPORTING_TO_POS_ORG_LEVEL] [nvarchar](4000) NULL,
	[POSITION_ID] [numeric](15, 0) NOT NULL,
	[ACTING_POS_ID] [float] NULL,
	[REP_TO_POSITION_ID] [numeric](15, 0) NOT NULL
) ON [PRIMARY]
