CREATE TABLE [HR].[POSITION_HIREARCHY] (
    [POSITION_NAME]              NVARCHAR (4000) NULL,
    [POSITION_ORG_LEVEL]         NVARCHAR (4000) NULL,
    [ACTING_POSITION_NAME]       NVARCHAR (240)  NULL,
    [REPORTING_TO_POSITION_NAME] NVARCHAR (4000) NULL,
    [REPORTING_TO_POS_ORG_LEVEL] NVARCHAR (4000) NULL,
    [POSITION_ID]                NUMERIC (15)    NOT NULL,
    [ACTING_POS_ID]              FLOAT (53)      NULL,
    [REP_TO_POSITION_ID]         NUMERIC (15)    NOT NULL
);

