CREATE TABLE [HR].[XXHR_ORG_HIERARCHY_MV] (
    [ORGNAME]      NVARCHAR (240)  NOT NULL,
    [ORGID]        NUMERIC (15)    NOT NULL,
    [ORGTYPE]      NVARCHAR (30)   NULL,
    [BU_NAME]      NVARCHAR (4000) NULL,
    [BU_ID]        NVARCHAR (4000) NULL,
    [DIV_NAME]     NVARCHAR (4000) NULL,
    [DIV_ID]       NVARCHAR (4000) NULL,
    [DEP_NAME]     NVARCHAR (4000) NULL,
    [DEP_ID]       NVARCHAR (4000) NULL,
    [TEAM_NAME]    NVARCHAR (4000) NULL,
    [TEAM_ID]      NVARCHAR (4000) NULL,
    [SECTION_NAME] NVARCHAR (4000) NULL,
    [SECTION_ID]   NVARCHAR (4000) NULL
);

